package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.layout.BorderPane;

public class PrincipalController {
	@FXML
	private BorderPane contenedor;
	@FXML
	private Button botonOrange;
	@FXML
	private Button botonPink;
	@FXML
	private Button botonBrown;

	// Event Listener on Button[#botonRojo].onAction
	
	@FXML
    void cambiarFondo(ActionEvent event) {
        Button boton = (Button) event.getSource();
        String botonId = boton.getId();
        
        switch (botonId) {
            case "botonOrange":
          	
                contenedor.setStyle("-fx-background-color: orange;");
                break;
            case "botonPink":
                contenedor.setStyle("-fx-background-color: pink;");
                break;
            case "botonBrown":
                contenedor.setStyle("-fx-background-color: brown;");
                break;
        }


    }// TODO Autogenerated
	
}
